export const metadata = {
    title: 'Sann Opticals Limited | Services ',
    description: 'Generated by create next app',
  }

const Services = () => {
    return (
        <main>
            Services
        </main>
    )
}

export default Services